remote_theme: pages-themes/cayman@v0.2.0
source: "../"
plugins:
- jekyll-remote-theme
show_downloads: true
exclude: ['.github/', '.husky/', '.vscode/', 'api_doc_generation/', 'dist/', 'node_modules/', 'src/', 'docs/', '*.yaml', '*.js', '*.mjs', '*.json']
